import Button from "@mui/material/Button";
import Divider from "@mui/material/Divider";
import Paper from "@mui/material/Paper";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Modal from "../components/Modal";
import axios from "axios";
import Router from "next/router";

const Home: NextPage = () => {
  const initalValues = {
    firstName: "",
    lastName: "",
    email: "",
    phoneNumber: "",
  };

  const [formValues, setFormValues] = useState(initalValues);
  const [open, setOpen] = useState(false);

  const handleInputChange = (event: { target: { name: any; value: any } }) => {
    const { name, value } = event.target;
    setFormValues({
      ...formValues,
      [name]: value,
    });
  };

  const handleSubmit = () => {
    axios
      .post("/api/createUser", formValues)
      .then((res) => {
        console.log("res", res);
        setFormValues(initalValues);
        Router.push("/users");
      })
      .catch((err) => {
        console.error(err.message);
      })
      .finally(() => {
        handleClose();
      });
  };

  const handleClickOpen = () => {
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Veriphy Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container>
        <Grid item xs={12} md={3}></Grid>
        <Grid item xs={12} md={6}>
          <Typography
            variant="h5"
            textAlign="center"
            style={{ marginBottom: "2rem" }}
          >
            Login
          </Typography>
          <Divider />
          <Paper
            style={{
              marginTop: "1rem",
              padding: "2rem",
            }}
          >
            <Grid
              container
              spacing={2}
              justifyItems="center"
              alignItems="center"
            >
              <Grid item xs={12} md={6}>
                <TextField
                  id="firstName"
                  name="firstName"
                  label="First Name"
                  type="text"
                  value={formValues.firstName}
                  onChange={handleInputChange}
                  fullWidth
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <TextField
                  id="lastName"
                  name="lastName"
                  label="Last Name"
                  type="text"
                  value={formValues.lastName}
                  onChange={handleInputChange}
                  fullWidth
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <TextField
                  id="email"
                  name="email"
                  label="Email Address"
                  type="email"
                  value={formValues.email}
                  onChange={handleInputChange}
                  fullWidth
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <TextField
                  id="phoneNumber"
                  name="phoneNumber"
                  label="Phone Number"
                  type="text"
                  value={formValues.phoneNumber}
                  onChange={handleInputChange}
                  fullWidth
                />
              </Grid>
              <Grid item xs={12}>
                <Button
                  variant="contained"
                  color="info"
                  fullWidth
                  onClick={handleClickOpen}
                >
                  Submit
                </Button>
              </Grid>
            </Grid>
          </Paper>
        </Grid>
        <Grid item xs={12} md={3}></Grid>
      </Grid>
      <Modal
        open={open}
        handleClose={handleClose}
        handleSubmit={handleSubmit}
      />
    </div>
  );
};

export default Home;
